type KafkaTopic {
  name: String!
  partitions: [KafkaTopicPartition!]!

  consumerGroups: [KafkaTopicConsumerGroup!]!
}

type KafkaTopicPartition {
  id: ID!
  offset: Float
  offsetHigh: Float
  offsetLow: Float
}

type KafkaTopicConsumerGroup {
  group: KafkaConsumerGroup!
  offsets: [KafkaConsumerGroupOffset!]!
}
type KafkaConsumerGroupOffset {
  partitionId: ID!
  offset: Int!
}
